# 文件名建议统一为 pull-request.yml
# 应用 test-build.yml 的 demo
# 要求 package.json 提供 site:preview，base 应为 '/'

# name: MAIN_PULL_REQUEST

# on:
#   pull_request:
#     branches: [develop, main]
#     types: [opened, synchronize, reopened]

# jobs:
#   call-test-build:
#     uses: kongying-tavern/docs/.github/workflows/test-build.yml@next
